implement all report in desktop
DevNight-CNX/covid-19-cnx pull request #46
Opened 2020-03-22 17:46 UTC by Elecweb

<img width="590" alt="Screen Shot 2563-03-23 at 00 42 18" src="https://user-images.githubusercontent.com/13183413/77256241-96926d80-6c9f-11ea-98db-19d79effeba0.png">
<img width="581" alt="Screen Shot 2563-03-23 at 00 42 05" src="https://user-images.githubusercontent.com/13183413/77256246-9a25f480-6c9f-11ea-9ffa-be6d72f2d5c4.png">
<img width="571" alt="Screen Shot 2563-03-23 at 00 39 10" src="https://user-images.githubusercontent.com/13183413/77256250-9b572180-6c9f-11ea-968e-784edace5b2a.png">

2020-03-22 17:49 UTC, akharawita approved these changes

2020-03-23 02:30 UTC, jedsada-gh requested changes
@Elecweb resolve conflict first

2020-03-23 03:29 UTC, Elecweb commented on src/pages/Home/components/News/index.js
> +            history.push('/report');
@Golfklub ปุ่มข่าวทั้งหมดกอล์ฟใส่ event tracker หรือยัง หรือพี่ rebase แแล้วหาย

2020-03-23 03:32 UTC, Golfklub commented on src/pages/Home/components/News/index.js
> +            history.push('/report');
ยังครับเดี๋ยวใส่พร้อมกับ #49 ครับพี่ merge ก่อนเลย

2020-03-23 05:12 UTC, merged